DROP TABLE IF EXISTS user;

CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
  age INT(11) NULL DEFAULT NULL COMMENT '年龄',
  email VARCHAR(100) NULL DEFAULT NULL COMMENT '邮箱',
  job VARCHAR(50) NULL DEFAULT NULL COMMENT '职务',
  department VARCHAR(50) NULL DEFAULT NULL COMMENT '部门',
  PRIMARY KEY (id)
);